name: Publish to Chrome Web Store

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Build Extension
        run: |
          ./scripts/app.sh
          ./scripts/data.sh

      - name: Package to ZIP
        run: cd dist && zip -r ../asli-chrome.zip *

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        timeout-minutes: 1 # Ultra-fast push
        continue-on-error: true
        with:
          action: "publish"
          client_id: ${{ secrets.CHROME_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
          zip_file: "asli-chrome.zip"
