name: Publish to Firefox AMO

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Build Extension
        run: |
          ./scripts/app.sh
          ./scripts/data.sh

      - name: Package to ZIP
        run: cd dist && zip -r ../asli-firefox.zip *

      - name: Deploy to Mozilla Add-ons (AMO)
        uses: kewisch/action-web-ext@v1
        timeout-minutes: 1 # Ultra-fast push
        continue-on-error: true
        with:
          cmd: sign
          source: asli-firefox.zip
          apiKey: ${{ secrets.WEB_EXT_API_KEY }}
          apiSecret: ${{ secrets.WEB_EXT_API_SECRET }}
          channel: listed
