name: Publish to Firefox AMO

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v2.x

      - name: Build Extension
        run: |
          deno task app
          deno task data

      - name: Package to ZIP
        run: cd dist && zip -r ../asli-firefox.zip *

      - name: Deploy to Mozilla Add-ons (AMO)
        uses: mozilla/web-ext-action@v1
        with:
          extension-file: asli-firefox.zip
          source-file: asli-firefox.zip
          api-key: ${{ secrets.WEB_EXT_API_KEY }}
          api-secret: ${{ secrets.WEB_EXT_API_SECRET }}
          extension-id: asli@subrat.lima
          dry-run: false
